#172499349: view all Users and One User
atlp-rwanda/knights-bn-backend pull request #15
Opened 2020-05-09 10:31 UTC by Kagorora

#### What does this PR do?

- A super administrator should be able to view all users and a single user.

#### Description of Task to be completed?

 When Logged as a super-admin

- [ ]  Endpoint to view all Users

- [ ] Endpoint to view one User

- [ ] Test endPoint

#### How should this be manually tested?

- Clone the project

       https://github.com/Stackup-Rwanda/knights-bn-backend.git

- Move to the branch

       git checkout ft-admin-view-allUsers-172499349

- Install all the dependencies and start the server

       npm i && npm run dev-start

-  Use the following credentials to log in as an admin

       email: superadmin@barefootnomad.com

       password: Niyonkuru@1

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

- [#172499349](https://www.pivotaltracker.com/story/show/172499349)

#### Screenshots (if appropriate)

- `super-admin` log in

 
<img width="1136" alt="Screen Shot 2020-05-09 at 12 25 11" src="https://user-images.githubusercontent.com/48021034/81471290-5b68e100-91f0-11ea-9709-ee50203d2b77.png">

- Search all Users on the system

<img width="1169" alt="Screen Shot 2020-05-09 at 12 25 30" src="https://user-images.githubusercontent.com/48021034/81471295-60c62b80-91f0-11ea-9f5b-a99d446acee2.png">

- Search one User on the system

<img width="1165" alt="Screen Shot 2020-05-09 at 12 25 44" src="https://user-images.githubusercontent.com/48021034/81471299-66237600-91f0-11ea-8761-6c0c6e268f50.png">

#### Questions:

- N/A

2020-05-09 11:48 UTC, EugeneMunya approved these changes

2020-05-09 11:53 UTC, T2Wil commented
User password should not be passed over to the client-side.
![image](https://user-images.githubusercontent.com/30593186/81472965-cf5cb680-91fb-11ea-97a6-2a0df8bba727.png)

just out of curiosity why are using email to get a specific user instead of passing user-id?

2020-05-09 13:43 UTC, T2Wil approved these changes

2020-05-09 17:49 UTC, kagabof requested changes
Please use in your controllers
ex:
```
try{

} catch(error){

}
```

2020-05-10 09:29 UTC, kagabof approved these changes
Well done

2020-05-10 09:29 UTC, merged